Name = input("Enter name:")
Branch = input("Enter branch:")
Gender = input ("Enter Gender:")
College = input("Enter College:")
Age = input("Enter Age:")
print (Name)
print (Branch)
print (Gender)
print (College)
print (Age)
